baseURL = 'https://wesleycamargo.github.io/'
languageCode = 'en-us'
title = 'Wesley Camargo'
theme = 'hugo-theme-stack'

[params]
    mainSections = ['post']
    featuredImageField = 'image'
    rssFullContent = true

    [params.footer]
        since = 2024

    [params.dateFormat]
        published = 'Jan 02, 2006'
        lastUpdated = 'Jan 02, 2006 15:04 MST'

    [params.sidebar]
        emoji = '👋'
        subtitle = 'Welcome to my blog'
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = 'img/avatar.png'

    [params.article]
        math = false
        toc = true
        readingTime = true
        [params.article.license]
            enabled = true
            default = 'Licensed under CC BY-NC-SA 4.0'

    [params.comments]
        enabled = false

    [params.widgets]
        [[params.widgets.homepage]]
            type = 'search'
        [[params.widgets.homepage]]
            type = 'archives'
            [params.widgets.homepage.params]
                limit = 5
        [[params.widgets.homepage]]
            type = 'categories'
            [params.widgets.homepage.params]
                limit = 10
        [[params.widgets.homepage]]
            type = 'tag-cloud'
            [params.widgets.homepage.params]
                limit = 10
        [[params.widgets.page]]
            type = 'toc'

    [params.colorScheme]
        toggle = true
        default = 'auto'

    [params.imageProcessing]
        [params.imageProcessing.cover]
            enabled = true
        [params.imageProcessing.content]
            enabled = true

[permalinks]
    post = '/p/:slug/'
    page = '/:slug/'

[menu]
    [[menu.social]]
        identifier = 'github'
        name = 'GitHub'
        url = 'https://github.com/wesleycamargo'
        [menu.social.params]
            icon = 'brand-github'

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
    [markup.highlight]
        noClasses = false
        codeFences = true
        guessSyntax = true
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4
